tasks:
  - init: docker-compose build
  - command: docker-compose up

ports:
  - name: Jenkins-quickstart
    port: 8080
    onOpen: open-browser

vscode:
  extensions:
    - ms-azuretools.vscode-docker
