tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up


ports:
  - port: 2376
    onOpen: ignore
  - port: 8080
    onOpen: open-browser

vscode:
  extensions:
    - ms-azuretools.vscode-docker